apiVersion: v1
data:
    password: ENC[AES256_GCM,data:Apb5dKLXUrI=,iv:MrAjvZ/gY1ZJdDj1WAQlKxhLH/crwlKHSw57Z7Q7ZPY=,tag:mFeHE085doKPBLXX/Kw/sQ==,type:str]
    user: ENC[AES256_GCM,data:R2Q3ApxuEyg=,iv:AO9sxOdC70AWS2bJDIFXYOphak2siXMwZt7WRr6eBSI=,tag:wYxHPtAjwo42YxgKPg+u/A==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQjEwZWh3SytuTitwcDFR
            U1YxNC9RN0pQWnhsTTVpODM3em9YdGhNZlhrCnloTVliRGJsaDU3S25vaHcyZFFM
            dzFWYnRUNE9TelJXRjJjWjRkZGpCaTAKLS0tIEV1U1FWdjVEcWlvbHgzZFprTXpX
            WXFURENnazFmYlR5ai9sT1o1U0tZYnMK7ZvZAl2LPNzA4jTnSaHXTo6OQwQgCiUA
            l0IjIhIHf+2ZIxlYKsfjPdZ0ZUt+PG67z/AzCZHcVwU/BgV30v9E8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v4pkpl5x2ta8ps2lfzxpws88wyqgqzk9u5rpfwnwkt9a560suyuqmaz65a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T20:43:32Z"
    mac: ENC[AES256_GCM,data:RxotQbCDRWQDFocnqPTJZc0eVBJ8Wp+LAVNvWb+ncC3eRqSdUjLLHTH+B7YZsjc1J817NTJSkBxKcRYgvVHsO4HoOrKCx8t2Lt1gkmMC9wBQkv8y7fgAMhsfeqku8jPT6Gg2wHVwJNn3onx4v9x/MAf7K36kqjLO8BtPU9kB1do=,iv:RHm1WIktwCbBzZGAEn38xrcBzCRTf6V/bLM1CmZog44=,tag:S1zbb5I3C7MS2LMGp/ck3A==,type:str]
    version: 3.13.1
