apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laf-output-data
  namespace: laf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laf-model-data
  namespace: laf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
