apiVersion: v1
data:
  credentials.json: ENC[AES256_GCM,data:OIobc8/ZnYH3H+hxlH7v7+yStA+NymDNOIXFbgake2VPU5/fsYQVdTtgxeB4vjZTGLB1GNkeQu+A+vskaILMXgMTloKKHixGTLKdk8A/aJQa9RA82wZePrLAW2kT9SDEmiocbsBKiNfXVURtC3CAGKNWhqUL/PPcstsc/h9SAh01ilsQolJ65pHMTVauIYZXWGILJdQ+pqvHu6w950JrBBilz/SYKAOA3oSYuJia1tWt63W1AVkJd4I1DMRfsNDVOstkM2q0mjWzHVTaiHpXl+4h3g5lxQxi4u7oFNJKhPka9nc63/CNb2MlFXA=,iv:5i9pMZWkLxXQUwFt9HDQ86XRAR7H/fOjzljmBXC2HWo=,tag:4WDoCT+AYHqMXy6NcohFyQ==,type:str]
kind: Secret
metadata:
  name: audiobookshelf-tunnel-credentials
  namespace: audiobookshelf
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQkNFZGtsNjFFWnAxd0cv
        WVAwVks5cjZ5M2F4d1NrQXZDQXY0cGZnVkR3Cm5ESnVTTCt0R01vbFM4azJkamZh
        aDNMM1k1MlVvaWQ3QlRxSWM5d1V3ckUKLS0tIE1oVng3QThoTCtVN2pPZWVwTTE4
        em9jTm1CRzlQTVJQNnpEQ2VDL1dnQjgKxqcobOuOJVq0RbObBwsD0AJI8maTZlAP
        1uVQwQmioD3Dk4Y34SG3upHHqcr0k7IWM0/7GWVl5hCV1wHTpirE3w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1v4pkpl5x2ta8ps2lfzxpws88wyqgqzk9u5rpfwnwkt9a560suyuqmaz65a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-21T21:56:07Z"
  mac: ENC[AES256_GCM,data:/UrQpSEh5eRlnNVvvrFByB5x1NoPg8XZ9N9rLfv9l+BBNP7NLI9tMsjH5pinROIcIDfWMVoJib3r6hDnY1CCmUnusYyns6ol5Wb4d1KwaoWHs7xZ0GH81AQ8xmC2mUJlkygScCp0K88uwNpHdAHsXFTvZS4AA/CSIfOj1bAoDFM=,iv:+i/nTlN2I+Bx0C4C3kBS/fyLlgYMpcW59K+vrXK3/QU=,tag:vlmYFc7lAjoXYb0qPaF3mA==,type:str]
  version: 3.13.2
