apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:k31cxd3Ahigi8fivmVjT58HXrD1ezd1BMnwZZti+3VtyWX2/z/N9Nl6x0aqanUHhXDsAqtYOCluxYdEv/cjE6+hawX3bo/XvikpuaKcImVpbWOvXky+FLKrTketOgDcm2wFW4Iu+FOgR7753Nq6B0B7d/FpZIKxIE0NkIVZDkb8qqjJ6/3iReTnG1JJX5zFuuspvbuz6JBAucuHPatHl2fy6uZAUq09b+jvdxFfFOs17Lgq0aqe3Kl2SZ+Nzc2+P3tumJBbJux4fqyOtx5YggYmTY6BOI1Tid/qvcnh2NijFoOrlyQ448sKvzTs=,iv:hmJOFMZ3fySVbdwZG9sD3vilVaCqVD+dN8XjxsA2yAQ=,tag:lQp0LMTKOeQ95FsNg3h+gw==,type:str]
kind: Secret
metadata:
    name: laf-tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOTUyak12U2o2TGpEOUJP
            NFVWZHFIa09nenBLL2lUaU93YkhEZHR5UkNNCnkxZzZ2a3g4Smh4NW9WZ0l2azlB
            OFNLTyszNENSZkxsMThpY0U5QlBDcXMKLS0tIHRXUDNaUDdXZ3F1ZGZRYWRvMWpo
            YThRMk1aZS91MC9XWVRaUWtaNno0WkkKvrhBC5LGMVbGAcjR8jufElSNnSAi/9zB
            IZWX8XGedSnqbPkOCJoUvxcfgS5S3DFZJ30flYczKwKxLhtNqIKPVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v4pkpl5x2ta8ps2lfzxpws88wyqgqzk9u5rpfwnwkt9a560suyuqmaz65a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T11:55:47Z"
    mac: ENC[AES256_GCM,data:+N7C2NErvhZso3Cz8Fg3czbTxP+iZkkI1NikgXQnm03v1zy0MJxZP1DT7i4IpEcP9HeaVBOh8R62jIfCzlXUA8SzHMOk12NuPXjPVG5054+jbY36nzNYhGZqEhk2hP/ASaywC/L9TCkvbeD7i/K4MlX0sYffE/tn0udl5Ta1WzU=,iv:ArbVeHYPa7hbdrmYTj3goIAdpdtPaxO6b2hZmLnZLaM=,tag:8hf6psz/YMaEfM32LlTuIg==,type:str]
    version: 3.13.3
