apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:ulbnTNRhrUWwRiV2MuzTdSLCEs87EFcms7i8Fv843v+ZeJndQIdyiykTfXR6cxMh7jzFHUgKeJSBjI21SHLlqvaDUSKImGMNcsc4c6omE3JkuRT+x7Kufl25PzdNoof56AXw8j6p4cTiullwCQr4x0hRHhL39R3OpU3iCr8CRRXen5pxHEygGHWNuzR/Yuagh+MwczCMO0ypw2dFYEOHxNMCldLq0RFjzsbM3kkQPm9+4XBybXRJLK4gerNREJxZZMqe1fhnhzj+OhH0IVNrM1lEiephku4VJBv0z4XUh35b1/Mi5YJZUawm28E=,iv:kUbvEenEwOn0/rOq7Eitar2Ol99nQbR6Inc64peUYNQ=,tag:djEF4SXVg+3gvmXESrgKVw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: linkding
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SHB1M3VKYy9QUjdiSGpy
            RytaN0VWZ0V3UzJ0YTAwa25ieURDQjg4b3hBCjU3VlhzNlo5TVhRYVZvVFBKbTA3
            TktVbTlVLzRyd0VJN2dlQzJncmRKTlEKLS0tIGU1UkY2TGRPZFQrQ09mUnM4R0NX
            TzNaanFGQ1hTZVpXRkdrVkNzYUZIaEUK4CKhtnfCg5RSJCfndxcnhBYtJR4tis+K
            manpfRQDm2ntR2fpl0jnDVTYyYcIZA+RipMk0Pp72X3t0rftyzYkHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v4pkpl5x2ta8ps2lfzxpws88wyqgqzk9u5rpfwnwkt9a560suyuqmaz65a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T11:06:10Z"
    mac: ENC[AES256_GCM,data:l7bJ5Uf1KHkb60grrl+BzJO9jjlHA/2z6WARO3Jg19rTD1RiqzuDar5zotC84QMFshf7KIBMC72KlhDdDRsTShkHB5HhC+NlepP1lfJP7R6SlA01DYkqkfSa92OsUhsj44NE6Ab/LONjw9YkVuAX4jS9PIYi6lu+xc61Uewykq4=,iv:rIYzBAY74B1dbuy3WIFTHtmmgqDkWSVtyBGlKW7hzAc=,tag:PAyVw1zypNOaQD3maVd3uw==,type:str]
    version: 3.13.1
