apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:e0lgzorv6+HpZb1a,iv:vLYZseUXd+GEU28YOiklHXClEGe8y2eY94A8mSm71Lo=,tag:fq8YIAS1/Dmv7iPSY4IEyA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:ik43muorSNFtTNqczPtQQTqEqHM=,iv:nOf1CqrStjo5B9jrFlZ7neBm8UdxsoLdFJb554Xob8g=,tag:bBfJat3V0lEgmPKok1XCfg==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeFhDVEtCL2s3SFJ6Mk1r
            cmdtQXk1dUZ3TXcrQUl2UXA1d0hWalMyK1ZzClFBcXlaUmpjcjNmZnhXWjVxSVd6
            c2k4aWJmMmlkcTZwVmFiTi9ta2NFUFEKLS0tIGNNNDVjdm1kdWd0ZTBXK3RUaGJ6
            SHlQZHZYL0RNMTdoYUtST2lvRVdkczAKFNf8MODpCHnwuhc0zt7S88DLtxwbSExU
            dGW4/JzrO1SN3wsPLGDp2JP5UZdqaFXIWu0re/r0+bL9ULKa4iu46g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v4pkpl5x2ta8ps2lfzxpws88wyqgqzk9u5rpfwnwkt9a560suyuqmaz65a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T14:22:02Z"
    mac: ENC[AES256_GCM,data:VYjtDARU/W9+oBQREVNE2T2zGrqbX80/EhB4XLs9NfGubRCs/dXwsOSkDhOV8QirWYZkP+A1UcBtaLdE1p3OWODwFCE/hEVOqPyggx+DVqWjrKSkHNVi1gX3gtJWyUDAQlPeYfLOdi/ybhCWRzwx9+4SeLxzymqKI380eoD3m0Q=,iv:RnyuctRab0C+w0nFdaaR/jinDM9qacYryDQeaFM/85w=,tag:Z5hor2HMIea+cAE/CGJ/HA==,type:str]
    version: 3.13.1
