apiVersion: v1
kind: Secret
metadata:
    name: k3s-node-token
    namespace: kube-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:vseefs3hcijN4vjh2Chvp3cphDfMg2W5cQgaep/POoPk/hBiCOnF5lR2p3QpuNYiqURj1ExxanAu8Pq9EWGmgmUxBXyx31GM/Q/fAQYJORyAqbhC4uWQaSfKuIF5XVwjIGHN61wHv8LXhYVk,iv:xOb+68/lPutoiHnEv5qhlrGIqkaskU/1rCqUOVGPXLk=,tag:TeJwV5lnHzr6Wdm/uycKKg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTmFOcWdhZEo5WUFtR0pV
            c0JzUVBzcFJ3S29HVzdzNlg3cVJlNU40ckFNCnQrSVBLaFNLVENqR3lrVDNuRjFZ
            c3BwaGRLaXNsWjdLQXVOZjZuQ0FjVnMKLS0tIFdDUytKWFhvM2NmKzVBbHRlWFlF
            ZE1vR3FtTW45VkRDVXN2Wlk0dGZjRkkKqkVCMDCAlk35X2Hyb3ZaVbK+piBiZXgP
            rf1x1Gkw6ir6OLFeD5K2Ly+u9pug7a2VhRPdsF4Zsi2QcP0cMv2olQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v4pkpl5x2ta8ps2lfzxpws88wyqgqzk9u5rpfwnwkt9a560suyuqmaz65a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T19:48:15Z"
    mac: ENC[AES256_GCM,data:KLwOncex/4TJR3RZljd5a0xLu2OB/akYROVj5JBuCiCUJwsbGiTchbms8lLPbOYUVDuoY9X9rCg32KYEZwaxk+Mkz3j5iTCmiViiGLxFVEhOKe5/VxqfhEtLVPcJQwdCY4ViTirWFzg/HkLcqXe/zBrj0SvDYsJrRav5RAaG0OE=,iv:U+20ictkoJWBRFZAR92moB8dCCOSO+oD2S+gueOcFUs=,tag:2M+wZ6EPi2m7W2dvfmpq+g==,type:str]
    version: 3.13.2
