apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:ThCu3FlZ83n7AbG4QFtKrFQlt9AXmilGfyZHBOlqvH/9uu112FlCNewXVALXFvcRDaRVecfG/FcJ/DN8ua1QsJJLl8pqvvGv/DQZHPwMNEA1cqCCAr0rPWuV3NJa+Y7HTvq3cgUfxH2vX/TqGHrPNjZcGjLYa3EkCru/ow==,iv:cTpM/04N6MBl4TjyS57EWijyCEs8lNgMwosrXX+lisw=,tag:/xhyUSg+tp++BF6eQs9i/A==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
    namespace: renovate
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlb05nVmRjL0R5R01CaE1p
            NzYzQlhCV0ZBYXpmZGdZVlhhZjI4RldJMVM0ClRhTnV0UURsN3ZST3BqSy81UnlX
            YVRwcm8rSytCZG1wbmxSWUQyQlN5SXcKLS0tIFFubEFaTDE2V3VlV2pDaHdBWTdw
            VnZmcTRpRWpBK3Mxa1hHSGFyQmRoRlkKsMMG3+2JVEei/hlgGsSNf/Din++oHfo0
            jGxBiKmA6bcXF0t7/TIrDyC/uzS/rXXlTSAJtp5nZv0sYNWNq+MPag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v4pkpl5x2ta8ps2lfzxpws88wyqgqzk9u5rpfwnwkt9a560suyuqmaz65a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T10:35:59Z"
    mac: ENC[AES256_GCM,data:2huM+OsOmm/Ll9+BNBUhzKrdiCo7xnOyJBYr2JpFD5AQ11ST7tTA8/6bT65Ousx7SXq4O9N/fZm6y6kzHXB3kLBwzVfE7MX7/vX/jxDrb6uereFJ7khq4Kh3yETeXKRftVAEBu76RgrMZYKt0VlhSBgJdAALq6i0IWNkEVKL3gI=,iv:jxRzKgH8YB+d0fuQ0mcr0UpLNbCusQXuUCzBuJwjh9g=,tag:lzagwajAvrLolw9gnmSF8w==,type:str]
    version: 3.13.2
